# ---------------------------- Language Map ----------------------------
language_code_map = {
    "English": "en",
    "Arabic": "ar",
    "Bengali": "bn",
    "Chinese (Simplified)": "zh",
    "Chinese (Traditional)": "zh-tw",
    "French": "fr",
    "German": "de",
    "Hindi": "hi",
    "Indonesian": "id",
    "Italian": "it",
    "Japanese": "ja",
    "Javanese": "jv",
    "Korean": "ko",
    "Malay": "ms",
    "Persian (Farsi)": "fa",
    "Portuguese": "pt",
    "Russian": "ru",
    "Spanish": "es",
    "Swahili": "sw",
    "Tamil": "ta",
    "Telugu": "te",
    "Turkish": "tr",
    "Urdu": "ur",
    "Vietnamese": "vi",
    # Indian regional languages
    "Assamese": "as",
    "Bodo": "brx",
    "Dogri": "doi",
    "Gujarati": "gu",
    "Kannada": "kn",
    "Kashmiri": "ks",
    "Konkani": "kok",
    "Maithili": "mai",
    "Malayalam": "ml",
    "Manipuri (Meitei)": "mni",
    "Marathi": "mr",
    "Nepali": "ne",
    "Oriya (Odia)": "or",
    "Punjabi": "pa",
    "Sanskrit": "sa",
    "Santali": "sat",
    "Sindhi": "sd",
    "Sinhala": "si",
    "Tibetan": "bo"
}